defaults:
  provider: openai
  model: gpt-4o
  fallback_model: gpt-3.5-turbo
  temperature: 0.7
  max_tokens: 2000
  timeout: 30

per_task:
  normalize_name:
    provider: openai
    model: gpt-3.5-turbo
    temperature: 0.3
    max_tokens: 500
    
  extract_site_info:
    provider: openai
    model: gpt-3.5-turbo
    temperature: 0.5
    max_tokens: 1000

  parse_inpi_docs:
    provider: openai
    model: gpt-4-turbo
    fallback_model: gpt-4o
    temperature: 0.2
    max_tokens: 3000

  ner_extraction:
    provider: openai
    model: gpt-4o
    temperature: 0.3
    max_tokens: 1500

  validate_consistency:
    provider: openai
    model: gpt-4-turbo
    temperature: 0.1
    max_tokens: 2000

  summarization:
    provider: openai
    model: gpt-4o
    temperature: 0.4
    max_tokens: 2500

  conflict_resolution:
    provider: openai
    model: gpt-4-turbo
    temperature: 0.2
    max_tokens: 1500

  reasoning:
    provider: openai
    model: gpt-4o
    temperature: 0.3
    max_tokens: 2000

  link_analysis:
    provider: openai
    model: gpt-4-turbo
    temperature: 0.2
    max_tokens: 2000

providers:
  openai:
    api_key_env: OPENAI_API_KEY
    base_url: https://api.openai.com/v1
    models:
      - gpt-3.5-turbo
      - gpt-4o
      - gpt-4-turbo
  
  anthropic:
    api_key_env: ANTHROPIC_API_KEY
    base_url: https://api.anthropic.com
    models:
      - claude-3-haiku-20240307
      - claude-3-sonnet-20240229
      - claude-3-opus-20240229
  
  mistral:
    api_key_env: MISTRAL_API_KEY
    base_url: https://api.mistral.ai
    models:
      - mistral-tiny
      - mistral-small
      - mistral-medium 